const USER_ROLES = {
    PARTICIPANT: 'participant',
    HOST: 'host',
    ORGANIZER: 'organizer',
    ADMIN: 'admin',
};

const createUserEntity = ({
    id,
    firebase_uid,
    email,
    name,
    avatar_url,
    role,
    bio,
    company,
    position,
    timezone,
    interests,
    points,
    level,
    is_blocked,
    created_at,
    events_organized_count,
    events_hosted_count,
    events_participated_count,
    comments_count,
    likes_count,
    favorites_count,
}) => ({
    id,
    firebase_uid,
    email,
    name,
    avatar_url,
    role,
    bio: bio ?? null,
    company: company ?? null,
    position: position ?? null,
    timezone: timezone ?? 'Europe/Kyiv',
    interests: interests ?? null,
    points: Number(points ?? 0),
    level: Number(level ?? 1),
    is_blocked: Boolean(is_blocked),
    created_at,
    events_organized_count: Number(events_organized_count ?? 0),
    events_hosted_count: Number(events_hosted_count ?? 0),
    events_participated_count: Number(events_participated_count ?? 0),
    comments_count: Number(comments_count ?? 0),
    likes_count: Number(likes_count ?? 0),
    favorites_count: Number(favorites_count ?? 0),
});

module.exports = {
    USER_ROLES,
    createUserEntity,
};
